### ISSUE TITLE
How to understand ExampleUdpServer.java?

### ISSUE THREAD

**Issue by bglmmz** [Shevchik/UdpServerSocketChannel#7]
Your code works great! I have the same case: UDP and private Channel for each client.
But, I'm not sure about somethings:
1. The parameter 'ioThreads'.
2. ServerBootstrap.group(new DefaultEventLoopGroup()), but not the ServerBootstrap.group(new NioEventLoopGroup(), new NioEventLoopGroup()).

So, could you please say more details?
Thanks.

**Comment by Shevchik** [comment]
1. It's the number of threads used for native socket data reading/writing.

The UdpServerSocketChannel itself is split to 2 parts.
 Io threads - threads the read/write bytes from/to system sockets.
 Worker threads that do user udp channel processing.

So the number of iothreads is the number of system sockets and threads that are used.
But be careful, the iothreads parameter only works on epoll capable platforms that support resuing udp port (i.e. Linux with kernel >= 3.9), and just defaults to 1 if not.

2. The reason why a signle argument event loop group method is used is because UdpServerSocketChannel uses it's own NioEventLoopGroup or EpollEventLoopGroup based on ioThreads number, so you can't provide a custom boss event loop group.
The reason why DefaultEventLoopGroup is used is because user worker threads don't do any native scoket/reading writing, they only process user tasks and pipeline operations.

**Comment by bglmmz** [comment]
Thanks!

**Comment by bglmmz** [comment]
Sorry, I would like to ask more .
My worker threads will read/write a redis-cluster and a MySQL server，in this case,  the worker threads group should use NioEventLoopGroup?

**Comment by Shevchik** [comment]
The UdpChannel itself is compatible with any event loop group. But if you are using the event loop group only for UdpServerSocketChannel then you better stick to DefaultEventLoopGroup (because it only needs to execute tasks).

**Comment by bglmmz** [comment]
Oh, I'm still puzzled. 
But just let it be.
The code is working well.
